<div class="row">
    <div class="col-lg-12">
        <p>Enter your full name and date of birth below to see your age in years, days and hours.</p>
        <?php if (!is_null($errorMessages)): ?>
            <div class="alert alert-danger">
                <ul>
                <?php foreach ($errorMessages as $input): ?>
                    <?php foreach ($input as $message): ?>
                        <li><?php echo $message ?></li>
                    <?php endforeach ?>
                <?php endforeach ?>
                </ul>
            </div>
        <?php endif; ?>
        <form class="form-inline" method="post">
            <div class="form-group">
                <label class="sr-only" for="<?php echo \Application\Entity\Entry::FIELD_NAME ?>">Full name</label>
                <input type="text" class="form-control" id="<?php echo \Application\Entity\Entry::FIELD_NAME ?>" name="<?php echo \Application\Entity\Entry::FIELD_NAME ?>" placeholder="Full name">
            </div>
            <div class="form-group">
                <label class="sr-only" for="<?php echo \Application\Entity\Entry::FIELD_DOB ?>">Date of birth</label>
                <input type="text" class="form-control" id="<?php echo \Application\Entity\Entry::FIELD_DOB ?>" name="<?php echo \Application\Entity\Entry::FIELD_DOB ?>" placeholder="Date of birth (dd/mm/yyyy)">
            </div>
            <input type="submit" class="btn btn-primary" value="Add" />
        </form>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-lg-12">

        <?php if (count($existingEntries) < 1): ?>

            <div class="alert alert-warning">
                <p>No one has added their details be. Be the first!</p>
            </div>

        <?php else: ?>

            <?php if (!is_null($insertId)): ?>
                <div class="alert alert-success">
                    <p>Your age is below. See, you're not as old as you thought!</p>
                </div>
            <?php endif; ?>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($existingEntries as $entry): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($entry->getName()) ?></td>
                        <td><?php echo $this->intervalYearsDaysHours($entry->getDateOfBirth(), $currentDateTime) ?></td>
                        <td><?php echo $this->dateFormat($entry->getTimestamp(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, 'en_GB'); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        <?php endif; ?>
    </div>
</div>