<div class="row">
    <div class="col-lg-12">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($existingEntries as $entry): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($entry->getName()) ?></td>
                    <td><?php echo $this->intervalYearsDaysHours($entry->getDateOfBirth(), $currentDateTime) ?></td>
                    <td><?php echo $this->dateFormat($entry->getTimestamp(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, 'en_GB'); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>