<div class="row">
    <div class="col-lg-12">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($existingEntries as $entry): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($entry->getName()) ?></td>
                    <td><?php echo $this->escapeHtml($entry->getDateOfBirth()) ?></td>
                    <td><?php echo $this->escapeHtml($entry->getTimestamp()) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php echo $this->intervalYearsDaysHours(new \DateTime('1990-04-15'), new \DateTime()) ?>

    </div>
</div>